url: http://michelenasti.com

name: Michele Nasti

description: Full stack Developer with an eye for the web

baseurl: /blog

github_username: musikele

twitter_username: micnasti

linkedin_username: michelenasti

google_plus_username: MicheleNasti

facebook_username: musikele

avatar: michele_nasti.jpg