url: http://michelenasti.com

gems:
- octopress-paginate

permalink: pretty

pagination:	
  limit: false
  per_page: 10
  title_suffix: " (page :num)"
  reversed: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      paginate: true

name: Michele Nasti

description: Full stack Developer with an eye for the web

github_username: musikele

twitter_username: micnasti

linkedin_username: michelenasti

google_plus_username: MicheleNasti

facebook_username: musikele

avatar: michele_nasti.jpg

exclude: 
- .travis.yml 
- deploy_key*
- Gemfile
- Gemfile.lock
- deploy.sh
- compile.sh
- start.sh