url: http://michelenasti.com
siteurl: http://michelenasti.com

gems:
  - octopress-paginate
  - jekyll-last-modified-at

permalink: pretty

markdown: kramdown
highlighter: rouge

pagination:	
  limit: false
  per_page: 10
  title_suffix: " (page :num)"
  reversed: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      paginate: true
      comments: true
      author: musikele
      categories: italiano 

name: Michele Nasti

description: Full stack Developer with an eye for the web

github_username: musikele
twitter_username: micnasti
linkedin_username: michelenasti
google_plus_username: MicheleNasti
facebook_username: musikele
avatar: michele_nasti.jpg

exclude: 
- .travis.yml 
- deploy_key*
- Gemfile
- Gemfile.lock
- deploy.sh
- compile.sh
- start.sh