---
hide_body: false
is_partial: false
fields:
- name: paginate
  default: true
  label: Paginate
  type: boolean
  hidden: true
- name: comments
  default: true
  label: Comments
  type: boolean
  hidden: true
- name: author
  default: musikele
  label: Author
  type: text
  hidden: true
- name: category
  type: select
  label: Category
  description: Category
  hidden: false
  config:
    options:
    - Italiano
    - English
  default: Italiano
- name: tags
  type: tag_list
  label: Tags
  description: tags
- name: layout
  type: text
  hidden: true
  label: layout
  description: the layout
  default: post
  config:
    required: true
- type: text
  name: title
  label: title
  description: 'The article title '
  config:
    required: true
- type: datetime
  default: Invalid date
  label: date
  name: date
  config:
    date_format: DD/MM/YYYY
    required: true
- type: file
  name: header-img
  label: header image
  description: Header Image
- type: textarea
  name: description
  label: Description
  description: A description for social networks
  config:
    required: true
pages:
- come-creare-luoghi-di-lavoro-in-cui-le-persone-sono-felici-di-recarsi.md
- _posts/2018-06-18-get-the-list-of-files-blocked-by-a-process-in-linux.md
- _posts/2017-02-10-hey-javascript-function-take-this.md
- _posts/2017-08-09-vacanze-guida-alla-val-d-aosta-con-un-neonato.md
- _posts/2018-01-12-la-mia-esperienza-col-test-driven-development.md
- _posts/2018-01-09-i-trend-javascript-del-2018.md
- _posts/2017-12-01-batman-ha-ispirato-il-comic-sans-storia-di-un-font-che-tutti-odiano.md
- _posts/2017-11-17-why-nan.md
- _posts/2017-11-14-not-a-number-when-javascript-gets-crazy.md
- _posts/2017-10-30-cryptomining-and-websites-how-long-will-be-tolerated.md
- _posts/2017-09-19-come-capire-il-bitcoin-le-funzioni-crittografiche.md
- _posts/2018-04-16-ode-ai-libri-di-carta.md
- _posts/2018-04-05-un-programmatore-dovrebbe-continuare-a-programmare-nel-suo-tempo-libero.md
- _posts/2018-02-18-un-giro-nell-universo-react.md
- _posts/2018-01-18-perche-la-green-card-e-una-lotteria.md
- _posts/2018-01-06-essere-programmatori-e-vivere-di-progetti-propri.md
- _posts/2017-07-17-recensione-del-libro-codice-montemagno.md
- _posts/2017-03-23-deploy-a-nodejs-app-on-heroku-in-less-than-1-minute.md
- _posts/2018-06-05-libri-sei-proprio-il-mio-typo-la-vita-segreta-dei-font.md
- _posts/2018-05-06-proteggi-le-tue-applicazioni-express-con-helmetjs.md
- _posts/2018-04-24-startup-weekend-salerno-2018.md
- _posts/2017-03-21-l-inglese-tra-italiani-a-lavoro-e-una-scelta-sbagliata.md
- _posts/2017-03-14-two-easy-ways-perform-get-requests-in-nodejs.md
- _posts/2017-02-05-quali-sono-gli-svantaggi-nel-lavorare-da-casa.md
- _posts/2017-04-08-all-my-articles-about-testing-in-javascript-in-one-post.md
- _posts/2018-04-05-come-realizzare-un-form-esterno-es-assistenza-che-manda-dati-a-magnews.md
- _posts/2017-12-04-alla-scoperta-di-vue-js.md
- _posts/2017-11-20-growth-hacker-cos-e-intervista-a-raffaele-gaito.md
- _posts/2017-10-03-viviamo-tutti-in-una-grande-simulazione-aliena-sembra-di-no.md
- _posts/2017-08-18-due-tre-opinioni-sul-growth-hacking-da-uno-che-non-ha-mai-fatto-nulla-di-marketing.md
- _posts/2018-02-25-cosa-ho-imparato-dai-miei-sbagli-ossia-consigli-per-i-giovani-laureandi.md
- _posts/2018-02-02-risultati-sondaggio-i-programmatori-e-i-corsi-di-formazione.md
- _posts/2018-01-07-e-importante-conoscere-come-sono-fatte-le-librerie-che-usiamo.md
- _posts/2017-12-04-dovrei-partecipare-al-programma-erasmus.md
- _posts/2017-05-22-i-colloqui-di-lavoro-nelle-big.md
- _posts/2017-03-13-js-promises-description-pros-cons-of-this-es6-construct.md
- _posts/2017-03-01-quando-l-azienda-non-paga-gli-stipendi.md
- _posts/2017-02-25-the-javascript-event-loop-for-dummies.md
- _posts/2017-03-28-become-a-test-expert-in-nodejs-with-these-tricks.md
