---
pages:
- _posts/2017-09-19-come-capire-il-bitcoin-le-funzioni-crittografiche.md
- _posts/2017-08-18-due-tre-opinioni-sul-growth-hacking-da-uno-che-non-ha-mai-fatto-nulla-di-marketing.md
- _posts/2017-07-18-recensione-libro-io-trafficante-di-virus-ilaria-capua.md
- _posts/2017-08-09-vacanze-guida-alla-val-d-aosta-con-un-neonato.md
- _posts/2017-07-17-recensione-del-libro-codice-montemagno.md
- _posts/2017-05-22-i-colloqui-di-lavoro-nelle-big.md
- _posts/the-not-so-great-ruby-journey.md
- _posts/2017-04-08-all-my-articles-about-testing-in-javascript-in-one-post.md
- _posts/2017-03-28-become-a-test-expert-in-nodejs-with-these-tricks.md
- _posts/2017-03-23-deploy-a-nodejs-app-on-heroku-in-less-than-1-minute.md
- _posts/2017-03-21-l-inglese-tra-italiani-a-lavoro-e-una-scelta-sbagliata.md
- _posts/2017-03-14-two-easy-ways-perform-get-requests-in-nodejs.md
- _posts/2017-03-13-js-promises-description-pros-cons-of-this-es6-construct.md
- _posts/2017-03-01-quando-l-azienda-non-paga-gli-stipendi.md
- _posts/2017-02-25-the-javascript-event-loop-for-dummies.md
- _posts/2017-02-05-quali-sono-gli-svantaggi-nel-lavorare-da-casa.md
- _posts/2017-02-10-hey-javascript-function-take-this.md
hide_body: false
fields:
- name: paginate
  default: true
  label: Paginate
  type: boolean
  hidden: true
- name: comments
  default: true
  label: Comments
  type: boolean
  hidden: true
- name: author
  default: musikele
  label: Author
  type: text
  hidden: true
- name: category
  type: select
  label: Category
  description: Category
  hidden: false
  config:
    options:
    - Italiano
    - English
  default: Italiano
- name: tags
  type: tag_list
  label: Tags
  description: tags
- name: layout
  type: text
  hidden: true
  label: layout
  description: the layout
  default: post
  config:
    required: true
- type: text
  name: title
  label: title
  description: 'The article title '
  config:
    required: true
- type: datetime
  default: Invalid date
  label: date
  name: date
  config:
    date_format: DD/MM/YYYY
    required: true
